build:
    cargo lambda build --release --arm64
    just zip
    echo "Build complete and created pdf_renderer.zip"

zip:
    rm -f pdf_renderer.zip || true
    cd ../../target/lambda/renderer && zip -r ../../../lambda_functions/renderer/pdf_renderer.zip bootstrap
    zip -r pdf_renderer.zip fonts